name: Publish to crates.io

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: 🚀 Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test (default)
        run: |
          cd http-derive
          cargo clippy -- -D warnings
          cargo test --release

      - name: 🧪 Test (all features)
        run: |
          cd http-derive
          cargo clippy --all-features -- -D warnings
          cargo test --all-features --release

      - name: 🚀 Publish crate (http-derive-impl)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd http-derive-impl
          cargo publish

      - name: 🚀 Publish crate (http-derive)
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cd http-derive
          cargo publish
